"""Ingest app: IListeningSocket protocol."""
from typing import Protocol

__all__ = ["IListeningSocket"]


class IListeningSocket(Protocol):
    def bind(self) -> None: ...
    def close(self) -> None: ...
    def unlink(self) -> None: ...
    def recvfrom(self, bufsize: int = 65536) -> tuple[bytes, str]: ...
    def sendto(self, data: bytes, addr: str) -> None: ...
