from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class ITransport(Protocol):
    def connect(self, path: Path) -> None: ...
    def send(self, data: bytes) -> None: ...
    def recv(self, timeout_ms: int) -> bytes | None: ...
    def close(self) -> None: ...
    @property
    def is_connected(self) -> bool: ...
